<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14</LangVersion>
    <OutputType>Library</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>

    <GenerateDependencyFile>true</GenerateDependencyFile>
    <ReferenceLibraryRoot Condition="'$(ReferenceLibraryRoot)' == '' And Exists('D:/AMPDatastore/Instances/cssharp01/counter-strike2/730/game/csgo/addons/counterstrikesharp/shared')">D:/AMPDatastore/Instances/cssharp01/counter-strike2/730/game/csgo/addons/counterstrikesharp/shared</ReferenceLibraryRoot>
    <ReferenceLibraryRoot Condition="'$(ReferenceLibraryRoot)' == ''">$(MSBuildProjectDirectory)/lib</ReferenceLibraryRoot>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    
    <PackageReference Include="CounterStrikeSharp.API" Version="1.0.369">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>

    <ProjectReference Include="vendor/PlayerSettingsCS2/PlayerSettingsApi/PlayerSettingsApi.csproj">
      <Private>false</Private>
      <PrivateAssets>all</PrivateAssets>
    </ProjectReference>
  </ItemGroup>

  
  <Target Name="StripRuntimesFolder" AfterTargets="Build">
    <RemoveDir Directories="$(OutDir)runtimes" />
  </Target>

  
  <ItemGroup>
    <None Remove="bin\**" />
    <None Remove="obj\**" />
    <None Remove=".github\**" />
    <None Remove="build\**" />
    <None Remove="**\*.pdb" />
    <None Remove="**\*.md" />
    <None Remove="**\*.yml" />
    <None Remove="**\*.yaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="vendor/**" />
    <EmbeddedResource Remove="vendor/**" />
    <None Remove="vendor/**" />
  </ItemGroup>
</Project>
